name: localization_text_generator
description: A sample command-line application.
version: 0.1.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk:  '>=3.1.5 <4.0.0'

# Add regular dependencies here.
dependencies:
  glob: ^2.1.2
  flutter:
    sdk: flutter
  args: ^2.5.0
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  path_provider: ^2.1.3
  yaml: ^3.1.2
  mason_logger: ^0.2.14

executables:
  glocalization: localization_text_generator

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
